const siteConfig = {
    url: process.env.NEXT_PUBLIC_SITE_URL,
    name: "",
    description: "",
    logoUrl: "",
    miniLogoUrl: "",
    links: {
        home: "/",
    },
    social: {
        facebook: "",
        instagram: "",
        twitter: "",
    },
    metadata: {
        keywords: "Template",
        author: "HashiraDevs",
    },
    nextMetada: {
        title: "Template",
        description: "Generated by create next app",
    },
};


export { siteConfig };
